namespace XM.Shared.API.Constants
{
    public enum AreaOfEffectType
    {
        AOEPerFogAcid = 0,
        AOEPerFogFire = 1,
        AOEPerFogStink = 2,
        AOEPerFogKill = 3,
        AOEPerFogMind = 4,
        AOEPerWallFire = 5,
        AOEPerWallWind = 6,
        AOEPerWallBlade = 7,
        AOEPerWeb = 8,
        AOEPerEntangle = 9,
        AOEPerDarkness = 11,
        AOEMobCircEvil = 12,
        AOEMobCircGood = 13,
        AOEMobCircLaw = 14,
        AOEMobCircChaos = 15,
        AOEMobFear = 16,
        AOEMobBlinding = 17,
        AOEMobUnearthly = 18,
        AOEMobMenace = 19,
        AOEMobUnnatural = 20,
        AOEMobStun = 21,
        AOEMobProtection = 22,
        AOEMobFire = 23,
        AOEMobFrost = 24,
        AOEMobElectrical = 25,
        AOEPerFogGhoul = 26,
        AOEMobTyrantFog = 27,
        AOEPerStorm = 28,
        AOEPerInvisibilitySphere = 29,
        AOEMobSilence = 30,
        AOEPerDelayBlastFireball = 31,
        AOEPerGrease = 32,
        AOEPerCreepingDoom = 33,
        AOEPerEvardsBlackTentacles = 34,
        AOEMobInvisibilityPurge = 35,
        AOEMobDragonFear = 36,
        AOEPerCustomAOE = 37,
        AOEPerGlyphOfWarding = 38,
        AOEPerFogOfBewilderment = 39,
        AOEPerVineMineCamouflage = 40,
        AOEMobTideOfBattle = 41,
        AOEPerStonehold = 42,
        AOEPerOvermind = 43,
        AOEMobHorrificAppearance = 44,
        AOEMobTroglodyteStench = 45,
    }

}