namespace XM.Plugin.Beast
{
    public enum BeastType
    {
        Invalid = 0,
        ScoutDrone = 1,
        DataRat = 2,
        ReconProbe = 3,
        CombatMech = 4,
        CyberCat = 5,
        SecurityBot = 6,
        WebCrawler = 7,
        HunterDrone = 8,
        PackAlpha = 9,
        BioTank = 10,
        MiningMech = 11,
        PlasmaBeetle = 12,
        CryoHound = 13,
        EchoWing = 14,
        ShadowUnit = 15,
        TitanFrame = 16,
        StormHawk = 17,
        FrostWalker = 18,
        VenomSynth = 19,
        SteelGuardian = 20,
        FlameWalker = 21,
        ThunderLizard = 22,
        HoloSpider = 23,
        WindRider = 24,
        SiegeFrame = 25,
        PhaseHunter = 26,
        IonWolf = 27,
        BattleWyrm = 28,
        PhoenixCore = 29,
        ApexMech = 30,
        StellarHound = 31,
        NullSpider = 32,
        StormReaper = 33,
        MagmaTitan = 34,
        CryoDragon = 35,
        PhotonStag = 36,
        VoidStalker = 37,
        OmegaFrame = 38,
        QuantumFox = 39,
        LeviathanMech = 40,
        VoidSerpent = 41,
        ArchangelUnit = 42,
        AlphaPrime = 43,
        TitanBeast = 44,
        WraithEngine = 45,
        CosmicEntity = 46,
        NightmareRider = 47,
        WorldEngine = 48,
        ChronoWyrm = 49,
        GenesisMachine = 50,
    }
}
