namespace NWN.Xenomech.API.NWNX.AdminPlugin
{
    public enum AdminOptionType
    {
        AllKillable = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_ALL_KILLABLE,
        NonPartyKillable = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_NON_PARTY_KILLABLE,
        RequireResurrection = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_REQUIRE_RESURRECTION,
        LoseStolenItems = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_STOLEN_ITEMS,
        LoseItems = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_ITEMS,
        LoseExp = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_EXP,
        LoseGold = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_GOLD,
        LoseGoldNum = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_GOLD_NUM,
        LoseExpNum = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_EXP_NUM,
        LoseItemsNum = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_ITEMS_NUM,
        PvpSetting = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_PVP_SETTING,
        PauseAndPlay = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_PAUSE_AND_PLAY,
        OnePartyOnly = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_ONE_PARTY_ONLY,
        EnforceLegalCharacters = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_ENFORCE_LEGAL_CHARACTERS,
        ItemLevelRestrictions = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_ITEM_LEVEL_RESTRICTIONS,
        CdkeyBanlistAllowlist = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_CDKEY_BANLIST_ALLOWLIST,
        DisallowShouting = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_DISALLOW_SHOUTING,
        ShowDmJoinMessage = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_SHOW_DM_JOIN_MESSAGE,
        BackupSavedCharacters = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_BACKUP_SAVED_CHARACTERS,
        AutoFailSaveOn1 = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_AUTO_FAIL_SAVE_ON_1,
        ValidateSpells = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_VALIDATE_SPELLS,
        ExamineEffects = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_EXAMINE_EFFECTS,
        ExamineChallengeRating = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_EXAMINE_CHALLENGE_RATING,
        UseMaxHitpoints = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_USE_MAX_HITPOINTS,
        RestoreSpellsUses = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_RESTORE_SPELLS_USES,
        ResetEncounterSpawnPool = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_RESET_ENCOUNTER_SPAWN_POOL,
        HideHitpointsGained = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_HIDE_HITPOINTS_GAINED,
        PlayerPartyControl = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_PLAYER_PARTY_CONTROL,
        ShowPlayerJoinMessages = Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_SHOW_PLAYER_JOIN_MESSAGES
    }

}
