namespace XM.Shared.API.NWNX.AdminPlugin
{
    public enum AdminOptionType
    {
        AllKillable = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_ALL_KILLABLE,
        NonPartyKillable = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_NON_PARTY_KILLABLE,
        RequireResurrection = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_REQUIRE_RESURRECTION,
        LoseStolenItems = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_STOLEN_ITEMS,
        LoseItems = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_ITEMS,
        LoseExp = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_EXP,
        LoseGold = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_GOLD,
        LoseGoldNum = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_GOLD_NUM,
        LoseExpNum = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_EXP_NUM,
        LoseItemsNum = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_LOSE_ITEMS_NUM,
        PvpSetting = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_PVP_SETTING,
        PauseAndPlay = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_PAUSE_AND_PLAY,
        OnePartyOnly = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_ONE_PARTY_ONLY,
        EnforceLegalCharacters = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_ENFORCE_LEGAL_CHARACTERS,
        ItemLevelRestrictions = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_ITEM_LEVEL_RESTRICTIONS,
        CdkeyBanlistAllowlist = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_CDKEY_BANLIST_ALLOWLIST,
        DisallowShouting = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_DISALLOW_SHOUTING,
        ShowDmJoinMessage = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_SHOW_DM_JOIN_MESSAGE,
        BackupSavedCharacters = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_BACKUP_SAVED_CHARACTERS,
        AutoFailSaveOn1 = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_AUTO_FAIL_SAVE_ON_1,
        ValidateSpells = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_VALIDATE_SPELLS,
        ExamineEffects = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_EXAMINE_EFFECTS,
        ExamineChallengeRating = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_EXAMINE_CHALLENGE_RATING,
        UseMaxHitpoints = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_USE_MAX_HITPOINTS,
        RestoreSpellsUses = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_RESTORE_SPELLS_USES,
        ResetEncounterSpawnPool = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_RESET_ENCOUNTER_SPAWN_POOL,
        HideHitpointsGained = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_HIDE_HITPOINTS_GAINED,
        PlayerPartyControl = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_PLAYER_PARTY_CONTROL,
        ShowPlayerJoinMessages = NWN.Core.NWNX.AdminPlugin.NWNX_ADMINISTRATION_OPTION_SHOW_PLAYER_JOIN_MESSAGES
    }

}
