namespace XM.Progression.Craft
{
    public enum RecipeType
    {
        Invalid = 0,

        Test = 1,

        #region Weaponcraft: 1-3000
        AurionAlloyDagger = 1,
        PantherClaws = 2,
        EtherCesti = 3,
        AurionAlloyBlade = 4,
        ResonanceBlade = 5,
        AshStriker = 6,
        AurionAlloyKnife = 7,
        CorrodedGreatblade = 8,
        MapleConduit = 9,
        PhantomFang = 10,
        CoarseShuriken = 11,
        AshenWarstaff = 12,
        VanguardCutter = 13,
        AurionAlloyMace = 14,
        AurionAlloyHammer = 15,
        ArcShuriken = 16,
        AurionAlloyAxe = 17,
        StormHarpoon = 18,
        Shadowpiercer = 19,
        TraineeWaraxe = 20,
        AurionAlloyKnuckles = 21,
        ZenithianArcblade = 22,
        RazorwingAxe = 23,
        AurionAlloyRod = 24,
        PhantomKnife = 25,
        TitanClaymore = 26,
        GaleforgedClaymore = 27,
        AurionAlloySpear = 28,
        SpathaTekEdge = 29,
        AshenPolearm = 30,
        InfernalCleaver = 31,
        Stormpiercer = 32,
        ArcDagger = 33,
        HivefangSpatha = 34,
        VulcanWarblade = 35,
        BrassstrikeKnuckles = 36,
        BrassArcblade = 37,
        BrassfangDagger = 38,
        WillowConduit = 39,
        BrassstrikeAxe = 40,
        TropicStrikers = 41,
        BilbronEdge = 42,
        WhisperfangDagger = 43,
        SparkfangEdge = 44,
        BrassfangClaws = 45,
        EtherScimitar = 46,
        HydrofangClaws = 47,
        ArcKnife = 48,
        MercenaryFang = 49,
        BrassforceRod = 50,
        VerdantHollyStaff = 51,
        TitanGreataxe = 52,
        BrassstrikeHammer = 53,
        VanguardBattalionSword = 54,
        GaleFang = 55,
        HydroCleaver = 56,
        FerriteSword = 57,
        ShadowfangBlade = 58,
        SparkfangDagger = 59,
        PrecisionClaws = 60,
        ArcbladeLongsword = 61,
        BonecleaverAxe = 62,
        UnmarkedGreatsword = 63,
        ZephyrClaws = 64,
        VenomfangBaselard = 65,
        DegenTek = 66,
        WarbornBlade = 67,
        VerdantHollyPolearm = 68,
        BrassstrikeSpear = 69,
        PulseTuck = 70,
        ObsidianFang = 71,
        VanguardShuriken = 72,
        SparkfangSpear = 73,
        TitanBroadsword = 74,
        YewConduit = 75,
        MothfangAxe = 76,
        TitanMace = 77,
        BoneforgedPick = 78,
        ShadowfangClaws = 79,
        ZephyrCutter = 80,
        AlloyKnuckles = 81,
        EtherFleuret = 82,
        WarbringerHammer = 83,
        EtherfangKukri = 84,
        ArcaneRod = 85,
        SteelKiljBlade = 86,
        TitanBattleaxe = 87,
        ToxinFang = 88,
        WingShuriken = 89,
        SanctifiedEdge = 90,
        ToxinKnife = 91,
        SkylarkEdge = 92,
        VanguardLance = 93,
        MythriteDagger = 94,
        ElmwoodWarstaff = 95,
        RangingFang = 96,
        PredatorClaws = 97,
        VanguardSplitter = 98,
        AbyssalBlade = 99,
        EremitesEtherWand = 100,
        ToxinKukri = 101,
        BonecrusherCudgel = 102,
        MythriteDegen = 103,
        VerdantSlayer = 104,
        SpikedMaul = 105,
        RaidersTomahawk = 106,
        TitanSpear = 107,
        ToxinCesti = 108,
        MythriteBlade = 109,
        VanguardFang = 110,
        EtherShuriken = 111,
        RavagerClaws = 112,
        CenturionCleaver = 113,
        SparkfangDegen = 114,
        EtherfangKris = 115,
        HydrofangTalons = 116,
        TwinfangAxe = 117,
        TyroWarKatars = 118,
        StrikersKnife = 119,
        TitanMaul = 120,
        ElmwoodPolearm = 121,
        RoguesJambiya = 122,
        ReapersFalx = 123,
        WarbornPick = 124,
        RiftTulwar = 125,
        LeviathanStaff = 126,
        MythriteClaymore = 127,
        SwiftclawSword = 128,
        WarKatars = 129,
        TempestFang = 130,
        ToxinfangClaws = 131,
        LongstrikeShuriken = 132,
        AscendantBlade = 133,
        MythriteRod = 134,
        ReapersVoulge = 135,
        MythriteKnife = 136,
        MythriteMace = 137,
        ToxinfangTalons = 138,
        HydroCleaver2 = 139,
        FractureFang = 140,
        TitanWaraxe = 141,
        OakfangCudgel = 142,
        RegalVanguardBlade = 143,
        TitanLance = 144,
        MythriteKnuckles = 145,
        InfernalDegen = 146,
        MythriteAxe = 147,
        ToxinWarKatars = 148,
        MythriteKukri = 149,
        SparkfangLance = 150,
        TitanGreatsword = 151,
        HallowedMaul = 152,
        WarbornHalberd = 153,
        CrescentShotel = 154,
        EtherwovenStraps = 155,
        ObeliskWarLance = 156,
        SparkfangBaselard = 157,
        WarcastersShuriken = 158,
        MythriteClaws = 159,
        SanctifiedDegen = 160,
        TitanClub = 161,
        OakwoodWarstaff = 162,
        TrainingBlade = 163,
        KhetenWarblade = 164,
        NoviceDuelistsTuck = 165,
        PassaddhiMysticStaff = 166,
        ArcstrikeAdargas = 167,
        NoviceDuelistsShuriken = 168,
        WarcastersAxe = 169,
        CombatCastersTalon = 170,
        BoneforgedRod = 171,
        OakwoodPolearm = 172,
        WarcasterDagger = 173,
        VeldtCleaver = 174,
        ArcFalchion = 175,
        HallowedMace = 176,
        QiResonanceStaff = 177,
        Cherryblade = 178,
        JuggernautMothAxe = 179,
        ZephyrWarblade = 180,
        ExecutionersFaussar = 181,
        TwilightFang = 182,
        TewhaReaver = 183,
        YagudoCryoShuriken = 184,
        InfernalEdge = 185,
        ReaversTabar = 186,
        CrimsonWing = 187,
        PredatorPatas = 188,
        BonefangKnife = 189,
        CobraWarblade = 190,
        RosethornConduit = 191,
        MusketeersPolearm = 192,
        VanguardKnightsSword = 193,
        TwinstrikeBlade = 194,
        CorsairsFang = 195,
        TacticianMagiciansConduit = 196,
        TacticianMagiciansTalons = 197,
        MusketeersEdge = 198,
        MythriteLance = 199,
        CometFangShuriken = 200,
        MythritePick = 201,
        LeucosReapersVoulge = 202,
        TundraWalrusStaff = 203,
        Nyxblade = 204,
        RoyalKnightArmyWarLance = 205,
        #endregion


        #region Armorcraft: 3001-6000

        #endregion


        #region Engineering: 6001-9000

        #endregion


        #region Fabrication: 9001-12000

        #endregion


        #region Synthesis: 15001-18000

        #endregion
    }
}
