namespace NWN.Xenomech.API.Constants
{
    public enum IPConstFeatType
    {
        Alertness = 0,
        Ambidextrous = 1,
        Cleave = 2,
        CombatCasting = 3,
        Dodge = 4,
        ExtraTurning = 5,
        Knockdown = 6,
        PointBlank = 7,
        SpellFocusAbj = 8,
        SpellFocusCon = 9,
        SpellFocusDiv = 10,
        SpellFocusEnc = 11,
        SpellFocusEvo = 12,
        SpellFocusIll = 13,
        SpellFocusNec = 14,
        SpellPenetration = 15,
        PowerAttack = 16,
        TwoWeaponFighting = 17,
        WeapSpeUnarm = 18,
        WeapFinesse = 19,
        ImpCritUnarm = 20,
        WeaponProfExotic = 21,
        WeaponProfMartial = 22,
        WeaponProfSimple = 23,
        ArmorProfHeavy = 24,
        ArmorProfLight = 25,
        ArmorProfMedium = 26,
        Mobility = 27,
        Disarm = 28,
        Whirlwind = 29,
        RapidShot = 30,
        HideInPlainSight = 31,
        SneakAttack1D6 = 32,
        SneakAttack2D6 = 33,
        SneakAttack3D6 = 34,
        ShieldProficiency = 35,
        UsePoison = 36,
        DisarmWhip = 37,
        WeaponProfCreature = 38,
        SneakAttack5D6 = 39,
        PlayerTool01 = 53,
        PlayerTool02 = 54,
        PlayerTool03 = 55,
        PlayerTool04 = 56,
        PlayerTool05 = 57,
        PlayerTool06 = 58,
        PlayerTool07 = 59,
        PlayerTool08 = 60,
        PlayerTool09 = 61,
        PlayerTool10 = 62
    }
}