
namespace NWN.Xenomech.API.Constants
{
    public enum VoiceChatType
    {
        Attack = 0,
        BattleCry1 = 1,
        BattleCry2 = 2,
        BattleCry3 = 3,
        HealMe = 4,
        Help = 5,
        Enemies = 6,
        Flee = 7,
        Taunt = 8,
        GuardMe = 9,
        Hold = 10,
        GroupAttack1 = 11,
        GroupAttack2 = 12,
        GroupAttack3 = 13,
        Pain1 = 14,
        Pain2 = 15,
        Pain3 = 16,
        NearDeath = 17,
        Death = 18,
        Poisoned = 19,
        SpellFailed = 20,
        WeaponSucks = 21,
        FollowMe = 22,
        LookHere = 23,
        Group = 24,
        MoveOver = 25,
        PickLock = 26,
        Search = 27,
        Hide = 28,
        CanDo = 29,
        CantDo = 30,
        TaskComplete = 31,
        Encumbered = 32,
        Selected = 33,
        Hello = 34,
        Yes = 35,
        No = 36,
        Stop = 37,
        Rest = 38,
        Bored = 39,
        Goodbye = 40,
        Thanks = 41,
        Laugh = 42,
        Cuss = 43,
        Cheer = 44,
        TalkToMe = 45,
        GoodIdea = 46,
        BadIdea = 47,
        Threaten = 48
    }
}
