
namespace XM.API.Constants
{
    public enum PoisonType
    {
        Nightshade = 0,
        SmallCentipedePoison = 1,
        BladeBane = 2,
        GreenbloodOil = 3,
        Bloodroot = 4,
        PurpleWormPoison = 5,
        LargeScorpionVenom = 6,
        WyvernPoison = 7,
        BlueWhinnis = 8,
        GiantWaspPoison = 9,
        ShadowEssence = 10,
        BlackAdderVenom = 11,
        Deathblade = 12,
        MalyssRootPaste = 13,
        Nitharit = 14,
        DragonBile = 15,
        SassoneLeafResidue = 16,
        TerinavRoot = 17,
        CarrionCrawlerBrainJuice = 18,
        BlackLotusExtract = 19,
        OilOfTaggit = 20,
        IdMoss = 21,
        StripedToadstool = 22,
        Arsenic = 23,
        LichDust = 24,
        DarkReaverPowder = 25,
        UngolDust = 26,
        BurntOthurFumes = 27,
        ChaosMist = 28,
        BebilithVenom = 29,
        QuasitVenom = 30,
        PitFiendIchor = 31,
        EttercapVenom = 32,
        AraneaVenom = 33,
        TinySpiderVenom = 34,
        SmallSpiderVenom = 35,
        MediumSpiderVenom = 36,
        LargeSpiderVenom = 37,
        HugeSpiderVenom = 38,
        GargantuanSpiderVenom = 39,
        ColossalSpiderVenom = 40,
        PhaseSpiderVenom = 41,
        WraithSpiderVenom = 42,
        IronGolem = 43,
    }
}